version: '3.8'

services:
  glpi_dashboard:
    container_name: glpi_dashboard_tv
    # IMPORTANTE: En Portainer, si usas 'Web editor', cambia '.' por la ruta ABSOLUTA
    # donde subiste los archivos. Ej: /home/tu_usuario/glpi_dashboard
    build: . 
    restart: always
    ports:
      - "8846:8846"
    volumes:
      # - ./logs:/app/logs
    environment:
      - TZ=America/Lima
      # Mapeo explícito de variables de Portainer al Contenedor
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_PORT=${DB_PORT:-3306}
    # Network mode host es opcional si la BD está en el mismo host y queremos acceder via localhost,
    # pero bridge suele ser mejor. Si la BD está en OTRO servidor, bridge está bien.
